#!/bin/bash
# Upgrade Table 4 (tab:geometry) / Table 6 (tab:ablation_selection) from the
# 5K-scale (100-sample, original Stage3+Stage4b) N-best geometry results to
# the final Stage3b (+ Stage4b) 25K configuration, point-cloud and STEP,
# N=1/3/5/10, same methodology as the existing 5K-scale run (scratch/
# geometry_nbest_100_{point,step}), just pointed at the new checkpoint and
# 25K test data. No new scripts needed -- reuses scratch/gen_nbest_candidates.py,
# scratch/repair_nbest_candidates.py, src/evaluate_execution_nbest.py,
# src/evaluate_geometry_nbest.py, src/scratch/aggregate_geometry_nbest.py
# unmodified (all already CLI-parameterized).
#
# Stage 1/2/4b checkpoints are unchanged from the formal 25K run; only the
# LoRA-IR checkpoint (lora_ir_25k_stage3b) and the P1a-repaired predicted_ir
# it produced (already generated by run_full_stage3b_pipeline.sh) are new.
set -euo pipefail
source /home/jizong/miniforge3/etc/profile.d/conda.sh
conda activate ai_dev
cd ~/workspace/MIRAGE/src

IR_S3B=outputs/lora_ir_25k_stage3b
S4B_DIR=outputs/qwen25_coder_1_5b_program_25k_stage4b
WORK=outputs/geometry_nbest_25k_stage3b
N=100

mkdir -p "$WORK"

for m in point step; do
  echo "=== [$m] N-best candidate generation (N=10, greedy + 9 temperature-sampled) ==="
  python scratch/gen_nbest_candidates.py \
    --modality $m \
    --ir-jsonl "$IR_S3B/predicted_ir_test_${m}_p1a.jsonl" \
    --lora-code-dir "$S4B_DIR" \
    --input-jsonl data/25k/test.jsonl \
    --output-jsonl "$WORK/nbest_${m}.jsonl" \
    --limit $N --num-candidates 10 \
    --max-length 1536 --max-new-tokens 1536

  echo "=== [$m] repair (extrude_on_face + P0) applied to every candidate ==="
  python3 scratch/repair_nbest_candidates.py \
    "$WORK/nbest_${m}.jsonl" "$WORK/nbest_${m}_repaired.jsonl"
done

cat <<'EOF'

=== Done (WSL side). Run these in Windows PowerShell (real Flluma/OpenCASCADE execution + geometry scoring): ===

$Root = "\\wsl.localhost\Ubuntu\home\jizong\workspace\MIRAGE\src"
$Work = "outputs\geometry_nbest_25k_stage3b"

foreach ($m in @("point","step")) {
  # Step 1: per-candidate build/validate/export gates (aggregate-only summary stats)
  & "C:\Workspace\Project\Paper\MIRAGE-V2\src\scripts\evaluate_execution_nbest.ps1" `
    -InputJsonl (Join-Path $Root "$Work\nbest_${m}_repaired.jsonl") `
    -OutputDir "C:\Workspace\Project\Paper\MIRAGE-V2\scratch\exec_nbest_25k_stage3b_${m}"

  # Step 2: Chamfer distance + F@1% geometry scoring. INDEPENDENT of step 1 --
  # evaluate_geometry_nbest.py re-runs its own 5 execution gates internally and
  # needs modality/point_path/step_path/all_candidates, which only the ORIGINAL
  # repaired-candidates file has (step 1's own output drops those fields). Do
  # NOT feed this step 1's output -- that produces a silent 0-rows-with-target
  # result (has_target=False for every row) with no error, only realized when
  # aggregate_geometry_nbest.py divides by zero.
  & "C:\Workspace\Project\Paper\MIRAGE-V2\src\scripts\evaluate_geometry_nbest.ps1" `
    -InputJsonl (Join-Path $Root "$Work\nbest_${m}_repaired.jsonl") `
    -OutputDir "C:\Workspace\Project\Paper\MIRAGE-V2\scratch\geometry_nbest_25k_stage3b_${m}"
}

Then aggregate (in WSL or a local Python with the same deps):
  python3 scratch/aggregate_geometry_nbest.py "/mnt/c/Workspace/Project/Paper/MIRAGE-V2/scratch/geometry_nbest_25k_stage3b_point/geometry_nbest_rows.jsonl"
  python3 scratch/aggregate_geometry_nbest.py "/mnt/c/Workspace/Project/Paper/MIRAGE-V2/scratch/geometry_nbest_25k_stage3b_step/geometry_nbest_rows.jsonl"

This prints the Table 4 headline (Median CD / Median F@1% per N=1/3/5/10) for both modalities.
EOF
